import type { RoadmapNode, RoadmapEdge } from '../types/roadmap';

const ts = new Date().toISOString();

export const demoNodes: RoadmapNode[] = [
  {
    id: 'goal-1',
    type: 'goal',
    position: { x: 0, y: 0 },
    data: {
      title: 'Nutzer kann Daten exportieren',
      subtitle: 'Umfassende Export-Funktionalitaet',
      description: 'Umfassende Export-Funktionalitaet fuer alle gaengigen Formate',
      status: 'now',
      level: 'goal',
      parentId: null,
      childrenIds: ['feature-1', 'feature-2'],
      collapsed: false,
      color: '#3B82F6',
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'feature-1',
    type: 'feature',
    position: { x: -150, y: 200 },
    data: {
      title: 'CSV-Export',
      subtitle: 'Konfigurierbares Trennzeichen',
      description: 'Export als CSV mit konfigurierbarem Trennzeichen',
      status: 'done',
      level: 'feature',
      parentId: 'goal-1',
      childrenIds: ['task-1', 'task-2'],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'feature-2',
    type: 'feature',
    position: { x: 200, y: 200 },
    data: {
      title: 'PDF-Export',
      subtitle: 'Professionell mit Branding',
      description: 'Professioneller PDF-Export mit Branding',
      status: 'now',
      level: 'feature',
      parentId: 'goal-1',
      childrenIds: ['task-3', 'task-4', 'task-5'],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'task-1',
    type: 'task',
    position: { x: -250, y: 380 },
    data: {
      title: 'Backend-Endpunkt implementieren',
      subtitle: '',
      description: '',
      status: 'done',
      level: 'task',
      parentId: 'feature-1',
      childrenIds: [],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'task-2',
    type: 'task',
    position: { x: -50, y: 380 },
    data: {
      title: 'Download-Button im Frontend',
      subtitle: '',
      description: '',
      status: 'done',
      level: 'task',
      parentId: 'feature-1',
      childrenIds: [],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'task-3',
    type: 'task',
    position: { x: 100, y: 380 },
    data: {
      title: 'PDF-Bibliothek integrieren',
      subtitle: '',
      description: '',
      status: 'done',
      level: 'task',
      parentId: 'feature-2',
      childrenIds: [],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'task-4',
    type: 'task',
    position: { x: 250, y: 380 },
    data: {
      title: 'Layout-Template erstellen',
      subtitle: '',
      description: '',
      status: 'now',
      level: 'task',
      parentId: 'feature-2',
      childrenIds: [],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'task-5',
    type: 'task',
    position: { x: 400, y: 380 },
    data: {
      title: 'Branding-Optionen implementieren',
      subtitle: '',
      description: '',
      status: 'next',
      level: 'task',
      parentId: 'feature-2',
      childrenIds: [],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'goal-2',
    type: 'goal',
    position: { x: 600, y: 0 },
    data: {
      title: 'Dashboard-Ansicht fuer Manager',
      subtitle: 'KPI-Darstellung fuer Management',
      description: 'Uebersichtliche KPI-Darstellung fuer das Management',
      status: 'later',
      level: 'goal',
      parentId: null,
      childrenIds: ['feature-3', 'feature-4'],
      collapsed: false,
      color: '#A855F7',
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'feature-3',
    type: 'feature',
    position: { x: 500, y: 200 },
    data: {
      title: 'KPI-Widgets',
      subtitle: 'Konfigurierbare Metriken',
      description: 'Konfigurierbare Widgets fuer verschiedene Metriken',
      status: 'later',
      level: 'feature',
      parentId: 'goal-2',
      childrenIds: [],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
  {
    id: 'feature-4',
    type: 'feature',
    position: { x: 750, y: 200 },
    data: {
      title: 'Filterfunktionen',
      subtitle: 'Zeitraum- und Team-Filter',
      description: 'Zeitraum- und Team-Filter',
      status: 'later',
      level: 'feature',
      parentId: 'goal-2',
      childrenIds: [],
      collapsed: false,
      color: null,
      createdAt: ts,
      updatedAt: ts,
    },
  },
];

export const demoEdges: RoadmapEdge[] = [
  {
    id: 'dep-1',
    source: 'goal-1',
    target: 'goal-2',
    type: 'dependency',
    style: 'solid',
    label: 'Voraussetzung',
  },
  {
    id: 'dep-2',
    source: 'feature-1',
    target: 'feature-2',
    type: 'dependency',
    style: 'dashed',
  },
];
